import {Organelle} from './Organelle';

export const ORGANELLS: Organelle[] = [{"accession":"AB237912.1","organismName":"Chromera velia","genus":"Chromera","superGroup":"Eukaryota","kingdom":"Protists","family":"Other Protists","type":"chloroplast"},
{"accession":"AM087200.3","organismName":"Solanum lycopersicum","genus":"Solanum","superGroup":"Eukaryota","kingdom":"Plants","family":"Land Plants","type":"chloroplast"},
{"accession":"AP012272.1","organismName":"Aspergillus luchuensis IFO 4308","genus":"Aspergillus","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"AP014607.1","organismName":"Kluyveromyces marxianus NBRC 1777","genus":"Kluyveromyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"AP017609.1","organismName":"Ramazzottius varieornatus YOKOZUNA-1","genus":"Ramazzottius","superGroup":"Eukaryota","kingdom":"Animals","family":"Other Animals","type":"mitochondrion"},
{"accession":"AP018713.1","organismName":"[Candida] auris JCM 15448","genus":"[Candida]","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"AP019407.1","organismName":"Monascus purpureus GB-01","genus":"Monascus","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"AY673996.1","organismName":"Agarophyton tenuistipitatum","genus":"Agarophyton","superGroup":"Eukaryota","kingdom":"Other","family":"Other","type":"chloroplast"},
{"accession":"CM001644.1","organismName":"Penicillium digitatum Pd1","genus":"Penicillium","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CM001645.1","organismName":"Penicillium digitatum PHI26","genus":"Penicillium","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CM002878.1","organismName":"Mortierella verticillata NRRL 6337","genus":"Mortierella","superGroup":"Eukaryota","kingdom":"Fungi","family":"Other Fungi","type":"mitochondrion"},
{"accession":"CM003133.1","organismName":"Sarcoptes scabiei","genus":"Sarcoptes","superGroup":"Eukaryota","kingdom":"Animals","family":"Other Animals","type":"mitochondrion"},
{"accession":"CM004311.1","organismName":"Saccharomyces cerevisiae GLBRCY22-3","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CM004524.1","organismName":"Cladophialophora carrionii KSF","genus":"Cladophialophora","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CM007644.1","organismName":"Zancudomyces culisetae COL-18-3","genus":"Zancudomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Other Fungi","type":"mitochondrion"},
{"accession":"CM008094.1","organismName":"[Candida] glabrata DSY562","genus":"[Candida]","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CM008107.1","organismName":"[Candida] glabrata DSY565","genus":"[Candida]","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CM008229.1","organismName":"Lomentospora prolificans JHH-5317","genus":"Lomentospora","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CM008263.2","organismName":"Pyrrhoderma noxium FFPRI411160","genus":"Pyrrhoderma","superGroup":"Eukaryota","kingdom":"Fungi","family":"Basidiomycetes","type":"mitochondrion"},
{"accession":"CM008827.1","organismName":"Paramicrosporidium saccamoebae KSL3","genus":"Paramicrosporidium","superGroup":"Eukaryota","kingdom":"Fungi","family":"Other Fungi","type":"mitochondrion"},
{"accession":"CM009589.1","organismName":"Rosa chinensis","genus":"Rosa","superGroup":"Eukaryota","kingdom":"Plants","family":"Land Plants","type":"mitochondrion"},
{"accession":"CM009590.1","organismName":"Rosa chinensis","genus":"Rosa","superGroup":"Eukaryota","kingdom":"Plants","family":"Land Plants","type":"chloroplast"},
{"accession":"CM009689.1","organismName":"Panicum miliaceum","genus":"Panicum","superGroup":"Eukaryota","kingdom":"Plants","family":"Land Plants","type":"chloroplast"},
{"accession":"CM010870.1","organismName":"Ooceraea biroi","genus":"Ooceraea","superGroup":"Eukaryota","kingdom":"Animals","family":"Insects","type":"mitochondrion"},
{"accession":"CM014102.1","organismName":"Labeo rohita","genus":"Labeo","superGroup":"Eukaryota","kingdom":"Animals","family":"Fishes","type":"mitochondrion"},
{"accession":"CM014335.1","organismName":"Schistosoma bovis TAN1997","genus":"Schistosoma","superGroup":"Eukaryota","kingdom":"Animals","family":"Flatworms","type":"mitochondrion"},
{"accession":"CM017530.1","organismName":"Mamestra configurata","genus":"Mamestra","superGroup":"Eukaryota","kingdom":"Animals","family":"Insects","type":"mitochondrion"},
{"accession":"CM017774.1","organismName":"Acer yangbiense","genus":"Acer","superGroup":"Eukaryota","kingdom":"Plants","family":"Land Plants","type":"mitochondrion"},
{"accession":"CM017775.1","organismName":"Acer yangbiense","genus":"Acer","superGroup":"Eukaryota","kingdom":"Plants","family":"Land Plants","type":"chloroplast"},
{"accession":"CM017889.1","organismName":"Cafeteria roenbergensis RCC970-E3","genus":"Cafeteria","superGroup":"Eukaryota","kingdom":"Protists","family":"Other Protists","type":"mitochondrion"},
{"accession":"CM017890.1","organismName":"Cafeteria roenbergensis Cflag","genus":"Cafeteria","superGroup":"Eukaryota","kingdom":"Protists","family":"Other Protists","type":"mitochondrion"},
{"accession":"CM017891.1","organismName":"Cafeteria roenbergensis BVI","genus":"Cafeteria","superGroup":"Eukaryota","kingdom":"Protists","family":"Other Protists","type":"mitochondrion"},
{"accession":"CM017892.1","organismName":"Cafeteria roenbergensis E4-10P","genus":"Cafeteria","superGroup":"Eukaryota","kingdom":"Protists","family":"Other Protists","type":"mitochondrion"},
{"accession":"CM017921.1","organismName":"Paragonimus westermani IND2009","genus":"Paragonimus","superGroup":"Eukaryota","kingdom":"Animals","family":"Flatworms","type":"mitochondrion"},
{"accession":"CM018571.1","organismName":"Pangasianodon hypophthalmus Indonesia","genus":"Pangasianodon","superGroup":"Eukaryota","kingdom":"Animals","family":"Fishes","type":"mitochondrion"},
{"accession":"CM018591.1","organismName":"Salix brachista","genus":"Salix","superGroup":"Eukaryota","kingdom":"Plants","family":"Land Plants","type":"mitochondrion"},
{"accession":"CM018592.1","organismName":"Salix brachista","genus":"Salix","superGroup":"Eukaryota","kingdom":"Plants","family":"Land Plants","type":"chloroplast"},
{"accession":"CM020933.1","organismName":"Perca fluviatilis","genus":"Perca","superGroup":"Eukaryota","kingdom":"Animals","family":"Fishes","type":"mitochondrion"},
{"accession":"CM020964.1","organismName":"Beauveria bassiana ERL836","genus":"Beauveria","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CM021150.1","organismName":"Caenorhabditis remanei PX506","genus":"Caenorhabditis","superGroup":"Eukaryota","kingdom":"Animals","family":"Roundworms","type":"mitochondrion"},
{"accession":"CM022150.1","organismName":"Frieseomelitta varia","genus":"Frieseomelitta","superGroup":"Eukaryota","kingdom":"Animals","family":"Insects","type":"mitochondrion"},
{"accession":"CM022905.1","organismName":"Plasmodium falciparum NF54","genus":"Plasmodium","superGroup":"Eukaryota","kingdom":"Protists","family":"Apicomplexans","type":"mitochondrion"},
{"accession":"CM022906.1","organismName":"Plasmodium falciparum NF54","genus":"Plasmodium","superGroup":"Eukaryota","kingdom":"Protists","family":"Apicomplexans","type":"apicoplast"},
{"accession":"CM023094.1","organismName":"Toxoplasma gondii RH-88","genus":"Toxoplasma","superGroup":"Eukaryota","kingdom":"Protists","family":"Apicomplexans","type":"apicoplast"},
{"accession":"CM024274.1","organismName":"Letharia lupina","genus":"Letharia","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP002712.1","organismName":"Eremothecium gossypii FDAG1","genus":"Eremothecium","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP004115.1","organismName":"Saccharomyces cerevisiae YJM1078","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006258.1","organismName":"Saccharomycetaceae sp. 'Ashbya aceri'","genus":"Saccharomycetaceae","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006474.1","organismName":"Saccharomyces cerevisiae YJM189","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006475.1","organismName":"Saccharomyces cerevisiae YJM193","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006476.1","organismName":"Saccharomyces cerevisiae YJM195","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006477.1","organismName":"Saccharomyces cerevisiae YJM244","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006478.1","organismName":"Saccharomyces cerevisiae YJM248","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006479.1","organismName":"Saccharomyces cerevisiae YJM270","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006480.1","organismName":"Saccharomyces cerevisiae YJM271","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006481.1","organismName":"Saccharomyces cerevisiae YJM320","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006482.1","organismName":"Saccharomyces cerevisiae YJM326","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006483.1","organismName":"Saccharomyces cerevisiae YJM428","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006484.1","organismName":"Saccharomyces cerevisiae YJM450","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006485.1","organismName":"Saccharomyces cerevisiae YJM451","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006486.1","organismName":"Saccharomyces cerevisiae YJM453","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006487.1","organismName":"Saccharomyces cerevisiae YJM456","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006488.1","organismName":"Saccharomyces cerevisiae YJM470","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006489.1","organismName":"Saccharomyces cerevisiae YJM541","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006490.1","organismName":"Saccharomyces cerevisiae YJM554","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006491.1","organismName":"Saccharomyces cerevisiae YJM555","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006492.1","organismName":"Saccharomyces cerevisiae YJM627","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006493.1","organismName":"Saccharomyces cerevisiae YJM681","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006494.1","organismName":"Saccharomyces cerevisiae YJM682","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006495.1","organismName":"Saccharomyces cerevisiae YJM683","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006496.1","organismName":"Saccharomyces cerevisiae YJM689","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006497.1","organismName":"Saccharomyces cerevisiae YJM693","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006498.1","organismName":"Saccharomyces cerevisiae YJM969","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006499.1","organismName":"Saccharomyces cerevisiae YJM972","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006500.1","organismName":"Saccharomyces cerevisiae YJM975","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006501.1","organismName":"Saccharomyces cerevisiae YJM978","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006502.1","organismName":"Saccharomyces cerevisiae YJM981","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006503.1","organismName":"Saccharomyces cerevisiae YJM984","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006504.1","organismName":"Saccharomyces cerevisiae YJM987","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006505.1","organismName":"Saccharomyces cerevisiae YJM990","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006506.1","organismName":"Saccharomyces cerevisiae YJM993","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006507.1","organismName":"Saccharomyces cerevisiae YJM996","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006508.1","organismName":"Saccharomyces cerevisiae YJM1083","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006509.1","organismName":"Saccharomyces cerevisiae YJM1129","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006510.1","organismName":"Saccharomyces cerevisiae YJM1133","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006511.2","organismName":"Saccharomyces cerevisiae YJM1190","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006512.1","organismName":"Saccharomyces cerevisiae YJM1199","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006513.1","organismName":"Saccharomyces cerevisiae YJM1202","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006514.1","organismName":"Saccharomyces cerevisiae YJM1208","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006515.1","organismName":"Saccharomyces cerevisiae YJM1242","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"CP006516.1","organismName":"Saccharomyces cerevisiae YJM1244","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"NW_007361658.1","organismName":"Colletotrichum graminicola M1.001","genus":"Colletotrichum","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"NW_008751656.1","organismName":"Exophiala dermatitidis NIH\/UT8656","genus":"Exophiala","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"NW_014013625.1","organismName":"Monoraphidium neglectum SAG 48.87","genus":"Monoraphidium","superGroup":"Eukaryota","kingdom":"Plants","family":"Green Algae","type":"mitochondrion"},
{"accession":"NW_014013626.1","organismName":"Monoraphidium neglectum SAG 48.87","genus":"Monoraphidium","superGroup":"Eukaryota","kingdom":"Plants","family":"Green Algae","type":"chloroplast"},
{"accession":"NW_014040924.1","organismName":"Trichosporon asahii var. asahii CBS 2479","genus":"Trichosporon","superGroup":"Eukaryota","kingdom":"Fungi","family":"Basidiomycetes","type":"mitochondrion"},
{"accession":"NW_015971901.1","organismName":"Plasmodium chabaudi chabaudi AS","genus":"Plasmodium","superGroup":"Eukaryota","kingdom":"Protists","family":"Apicomplexans","type":"mitochondrion"},
{"accession":"NW_017264706.1","organismName":"Saccharomyces eubayanus FM1318","genus":"Saccharomyces","superGroup":"Eukaryota","kingdom":"Fungi","family":"Ascomycetes","type":"mitochondrion"},
{"accession":"NW_017385168.1","organismName":"Plasmodium gaboni SY75","genus":"Plasmodium","superGroup":"Eukaryota","kingdom":"Protists","family":"Apicomplexans","type":"apicoplast"},
{"accession":"NW_017962150.1","organismName":"Plasmodium reichenowi SY57","genus":"Plasmodium","superGroup":"Eukaryota","kingdom":"Protists","family":"Apicomplexans","type":"apicoplast"},
{"accession":"NW_019223693.1","organismName":"Plasmodium yoelii 17X","genus":"Plasmodium","superGroup":"Eukaryota","kingdom":"Protists","family":"Apicomplexans","type":"apicoplast"},
{"accession":"NW_019223694.1","organismName":"Plasmodium yoelii 17X","genus":"Plasmodium","superGroup":"Eukaryota","kingdom":"Protists","family":"Apicomplexans","type":"mitochondrion"},
{"accession":"NW_021703914.1","organismName":"Besnoitia besnoiti Bb-Ger1","genus":"Besnoitia","superGroup":"Eukaryota","kingdom":"Protists","family":"Apicomplexans","type":"apicoplast"},
{"accession":"OVEO00000000.1","organismName":"Plasmodiophora brassicae","genus":"Plasmodiophora","superGroup":"Eukaryota","kingdom":"Protists","family":"Other Protists","type":"mitochondrion"}];